### PR TITLE
Implemented the delete functionality

### PR DESCRIPTION
**Pull request by yuvigrg**
Allows the users to delete streams

### CODE REVIEW

**Review by nimeshgurung — APPROVED** [review]
Nice one man. The api is almost complete now.

**Comment by yuvigrg** [comment]
> Nice one man. The api is almost complete now.

**Comment by yuvigrg** [comment]
> Nice one man. The api is almost complete now.

Ya, there is another branch which implements the add functionality. However, having problem with unit tests. Then its done.

**Comment by rajgurung** [comment]
Good work @yuvigrg.

**Pull request merged**
